### ISSUE TITLE
options

### ISSUE THREAD

**Issue by MargeryLab** [xjixzz/vadepth-net#1]
Hi, the options.py file is missing from the code

**Comment by xjixzz** [comment]
Thanks for pointing this out. I have added the options.py file.

**Comment by MargeryLab** [comment]
How do I get the absolute scale when testing, is the output of depth decoder relative depth? or is the network output  directly absolute depth when testing?

**Comment by xjixzz** [comment]
If the height_loss_weight in the file options.py is set to zero when training, the output of the depth network is relative depth and the median scaling method can be used to recover the absolute scale of depth.  We set the height_loss_weight as 1e-2 in our experiment so that the output of the depth network is absolute depth. I will update the README.md to provide details on training and evaluation as soon s possible.

**Comment by MargeryLab** [comment]
![image](https://user-images.githubusercontent.com/57980908/184582288-2881520e-d89c-40c8-9045-5bb4193d862b.png)
I tried to train the model, but found that convergence was extremely slow, even if I removed validation, and --batch_ size=8
