### ISSUE TITLE
Least squares solution

### ISSUE THREAD

**Issue by testingshanu** [xjixzz/vadepth-net#2]
Hi,

The paper mentions that least square is used to calculate n from the formula P_rect * n = 1.

May I know the theory of this equation ? Does n represent the normal of the plane ?

**Comment by xjixzz** [comment]
Hi, thank you for your interest in our work.

Yes, n is the normal vector of the plane. As described in the paper, "we can fit a plane Pl_rect that does not pass through the origin by solving the equation: P_rect * n = 1". Because the ground plane does not pass through the origin of coordinates，we have the plane Pl_rect = {(X, Y, Z)| aX +bY +cZ= d and d != 0} . Let Pi = P_rect(i) = (Xi, Yi, Zi) , i=0, ..., N_rect - 1, and n = (a/d, b/d, c/d)^T , if Pi ∈Pl_rect, then the plane equation can be formulated as Pi*n = 1, i.e. P_rect * n = 1, where P_rect is a matrix with the shape of N_rect * 3 instead of 3 * N_rect as described in the paper, I will update the manuscript to fix this issue.

**Comment by testingshanu** [comment]
Thank you for the explaination.
